INSERT INTO student (id,name,email) VALUES 
(1,'Valentine Gentry','elit.sed@nibh.co.uk'),(2,'Cole Atkins','Sed@Aeneaneget.edu'),(3,'Phillip Vasquez','a.tortor@a.com'),(4,'Perry Lott','euismod.urna@turpis.edu'),(5,'Amos Macias','suscipit@Classaptent.co.uk'),(6,'Warren Russell','cursus.non.egestas@gravidaPraesenteu.edu'),(7,'Blaze Williams','Proin@lobortis.co.uk'),(8,'Noah Puckett','Curae.Phasellus@porttitor.ca'),(9,'Zachary Alford','Integer.tincidunt.aliquam@et.com'),(10,'Cullen Colon','vel.lectus@eget.ca'),
(11,'Ross Atkinson','lacus.vestibulum.lorem@facilisis.ca'),(12,'Keaton Moore','Nulla@dictum.net'),(13,'Reuben Hurst','varius.Nam@mauris.net'),(14,'Daniel Santana','justo.nec@enimSednulla.net'),(15,'Troy Cochran','dictum.mi.ac@vitae.edu'),(16,'Marvin Richmond','pede.blandit.congue@sed.co.uk'),(17,'Ethan Yates','mauris.Integer@fringilla.ca'),(18,'Tanek Mercado','eu@nuncullamcorper.ca'),(19,'Samuel Reed','ante.Vivamus.non@Crasvulputatevelit.com'),(20,'Len Glenn','arcu.Curabitur.ut@arcuSed.org'),
(21,'Sean Chaney','facilisis@Vestibulumanteipsum.com'),(22,'Todd Mckee','ipsum@aliquet.com'),(23,'Paki Galloway','inceptos@Morbi.edu'),(24,'Emery Langley','ultrices.posuere.cubilia@et.org'),(25,'Berk Mueller','scelerisque.dui@temporarcu.co.uk'),(26,'Rogan Haney','magna.Duis.dignissim@amet.ca'),(27,'Reese Cabrera','velit.eu@tinciduntDonecvitae.com'),(28,'Peter Whitehead','vulputate@velitSed.co.uk'),(29,'Sawyer Hartman','erat@orciDonecnibh.org'),(30,'Ulric Carey','mi.fringilla.mi@facilisisnon.com'),
(31,'Omar Rasmussen','Donec.porttitor.tellus@tempuseuligula.org'),(32,'Damon Ferrell','nec.tempus@risus.org'),(33,'Oscar Elliott','mollis@Cras.co.uk'),(34,'Luke Clay','massa.Quisque.porttitor@tinciduntduiaugue.net'),(35,'Victor Ross','lacus.Etiam@leoin.co.uk'),(36,'Tyrone Spears','semper.Nam@Quisque.com'),(37,'Gray Hall','a@dolorFuscemi.ca'),(38,'Reed Reyes','Morbi@quam.org'),(39,'Noah Melendez','ultricies@porttitorerosnec.edu'),(40,'Anthony Dillon','tristique.pellentesque.tellus@amalesuadaid.edu'),
(41,'Palmer Holmes','Donec@blanditcongue.ca'),(42,'Valentine Riley','dolor.sit.amet@risus.ca'),(43,'Clinton Phelps','Morbi.sit.amet@Donec.net'),(44,'Byron Dixon','Proin@Etiamgravida.org'),(45,'Roth Greer','augue.ac.ipsum@et.edu'),(46,'Hasad Bartlett','nunc@elitpellentesque.ca'),(47,'Norman Kennedy','facilisis.vitae@apurusDuis.net'),(48,'Reed Ortega','Curabitur@consectetuermaurisid.co.uk'),(49,'Isaiah Castro','risus@tristiquepellentesque.co.uk'),(50,'Kelly Duke','mollis@volutpat.net'),
(51,'Darius Gentry','consectetuer@estNunc.co.uk'),(52,'Howard Cotton','ante@justoProinnon.edu'),(53,'Blake Mendez','pede.nec.ante@semperrutrum.com'),(54,'Thane Hopkins','Etiam@nunc.net'),(55,'Eric Cruz','neque@ipsumCurabitur.org'),(56,'Declan Hubbard','nonummy.ac.feugiat@lectusrutrum.org'),(57,'Jelani Eaton','lectus@nequepellentesque.ca'),(58,'Linus Hodges','amet.consectetuer.adipiscing@fringillaporttitor.net'),(59,'Ronan Walters','arcu.Curabitur@mattis.edu'),(60,'Isaiah Johnston','sagittis@hendreritneque.edu'),
(61,'Rudyard Melton','purus.sapien.gravida@dolordapibusgravida.co.uk'),(62,'Tiger Blankenship','a.felis.ullamcorper@Curabitur.co.uk'),(63,'Wesley Richardson','vitae.mauris@Nulla.com'),(64,'Xanthus Stuart','Donec.tempus.lorem@mauris.ca'),(65,'Abel Franco','Lorem@tortornibh.ca'),(66,'Dylan Chase','libero@SedmolestieSed.ca'),(67,'Amir Stephenson','mauris.id.sapien@Ut.ca'),(68,'Ryder Rice','imperdiet.non.vestibulum@habitant.ca'),(69,'Randall Mendez','mus.Aenean.eget@miAliquam.org'),(70,'Henry Mays','vulputate.mauris.sagittis@ipsumSuspendisse.edu'),
(71,'Justin Haley','dui.nec.tempus@intempuseu.net'),(72,'Ferdinand Carlson','dignissim@sitamet.ca'),(73,'Melvin Paul','auctor.Mauris@aliquet.edu'),(74,'Quinn Anthony','eget.nisi@et.net'),(75,'Xavier Sanders','felis@Donecfeugiat.org'),(76,'Flynn Wynn','molestie.in.tempus@loremeget.ca'),(77,'Victor Edwards','nulla.vulputate.dui@arcu.org'),(78,'Ferdinand Woodard','dolor.dapibus.gravida@mi.com'),(79,'Daquan Carter','dolor.dapibus.gravida@Sed.com'),(80,'Graiden Foster','eu.arcu.Morbi@vitaeorci.com'),
(81,'Upton Tyler','sollicitudin.orci@convallis.net'),(82,'Fuller Howard','facilisi@Maurisvel.org'),(83,'Merrill Nelson','eros.nec.tellus@eleifendCras.org'),(84,'Orson Abbott','convallis@vel.com'),(85,'Jerry Burton','Etiam.laoreet.libero@Nuncsed.org'),(86,'Allen Ward','enim.Suspendisse.aliquet@lacusvestibulumlorem.org'),(87,'Lucius Byrd','tellus.non.magna@miloremvehicula.edu'),(88,'Palmer Hartman','fermentum.arcu.Vestibulum@luctusfelispurus.edu'),(89,'Merrill Stark','luctus.et@acarcu.ca'),(90,'Hector Jefferson','Aliquam.fringilla@rhoncus.com'),
(91,'August Horne','posuere@etlacinia.com'),(92,'Reed Richardson','Cras@nunc.com'),(93,'Kieran Justice','nunc@Quisqueporttitoreros.org'),(94,'Drake Blanchard','feugiat@adipiscingelit.org'),(95,'Steven Pratt','Morbi.neque@egestasnuncsed.co.uk'),(96,'Aidan William','justo.nec@dolor.edu'),(97,'Todd Pitts','metus@malesuada.edu'),(98,'Grant Hardin','placerat.orci.lacus@liberoProin.net'),(99,'Drew Slater','ante.bibendum@egestashendrerit.ca'),(100,'Colby Prince','Integer.mollis.Integer@uterosnon.net');


INSERT INTO user_ca (id,login, password, name, admin) VALUES 
(1, 'antonio.junior', '$2a$10$HDfdzwUTcYJxKsT6p5NYSeYIvtL152sx1iAT3VLrSEIa7Vy1kFi9G', 'Antonio Junior', true),
(2, 'caua.lima', '$2a$10$HDfdzwUTcYJxKsT6p5NYSeYIvtL152sx1iAT3VLrSEIa7Vy1kFi9G', 'Caua Lima', false);